$(document).ready(function(){
    $(".btn1").click(function(){
        $("#in-1").slideToggle();
    });
    $(".btn2").click(function(){
        $("#in-2").slideToggle();
    });
    $(".btn3").click(function(){
        $("#in-3").slideToggle();
    });
    $(".btn4").click(function(){
        $("#in-4").slideToggle();
    });
    $(".btn5").click(function(){
        $("#in-5").slideToggle();
    });
});